
name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwxgtk3.2-dev
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y build-essential
          sudo apt-get install -y cmake
          sudo apt-get install -y gcovr

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: |
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

